# Generated by Django 3.2.dev20201130090728 on 2020-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('date_updated', models.DateField(null=True)),
                ('date_added', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
