# Generated by Django 3.2.dev20201130090728 on 2020-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldatacollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_data',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='url_data',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
